'use client'

import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { Separator } from '@/components/ui/separator'
import {
    Table,
    TableBody,
    TableCaption,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table'
import Link from 'next/link'
import { useParams } from 'next/navigation'

export default function PrivacyPolicyPage() {
    const params = useParams()
    const lang =
        typeof params?.lang === 'string'
            ? params.lang
            : Array.isArray(params?.lang)
              ? params?.lang[0]
              : 'en'
    const to = (path: string) => `/${lang}${path}`
    const lastUpdated = 'August 1, 2025'

    const dataMap = [
        {
            category: 'Account & Profile',
            examples: 'Name, email, password hash, language preference, shipping addresses',
            source: 'Provided by you',
            retention: 'While account is active and as required by law',
        },
        {
            category: 'Design Requests',
            examples:
                'Prompts, design briefs generated by Solar Pro2, selected variants (size/color), approval decisions',
            source: 'Provided by you and generated by our systems',
            retention: 'Up to 24 months to support reorders, disputes, and QA',
        },
        {
            category: 'Payment',
            examples: 'Payment intent IDs, last4, brand, billing ZIP (via Stripe)',
            source: 'Processed by Stripe; we store tokens/metadata only',
            retention: '7 years for tax and accounting',
        },
        {
            category: 'Orders & Fulfillment',
            examples: 'Order IDs, Printify item/variant IDs, tracking numbers, delivery status',
            source: 'Generated by our systems and Printify',
            retention: 'As long as needed for customer service and legal',
        },
        {
            category: 'Usage & Device',
            examples:
                'IP address, timestamps, pages visited, referrer, approximate location, device/browser info',
            source: 'Automatically collected',
            retention: '12 months for security and analytics',
        },
        {
            category: 'Support',
            examples: 'Messages, email threads, attachments (no customer uploads for designs)',
            source: 'Provided by you',
            retention: '24 months or until request resolved + 6 months',
        },
    ]

    return (
        <main className="bg-background text-foreground min-h-screen">
            <section className="mx-auto w-full max-w-5xl px-6 py-10 sm:py-14">
                <nav aria-label="Breadcrumb" className="text-muted-foreground mb-6 text-sm">
                    <ol className="flex items-center gap-2">
                        <li>
                            <Link href={to('')} className="hover:text-foreground hover:underline">
                                Home
                            </Link>
                        </li>
                        <li className="text-border">/</li>
                        <li>
                            <Link
                                href={to('//help')}
                                className="hover:text-foreground hover:underline"
                            >
                                Help
                            </Link>
                        </li>
                        <li className="text-border">/</li>
                        <li className="text-foreground">Privacy Policy</li>
                    </ol>
                </nav>

                <div className="flex flex-col gap-4">
                    <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">
                        Privacy Policy
                    </h1>
                    <p className="text-muted-foreground text-sm">Last updated: {lastUpdated}</p>

                    <Alert className="bg-card text-card-foreground">
                        <AlertTitle className="font-semibold">
                            Your privacy, our commitment
                        </AlertTitle>
                        <AlertDescription>
                            This policy explains how RealizeIt collects, uses, and shares your data
                            when you browse, create AI-generated designs, and purchase products
                            fulfilled via Printify for delivery in South Korea and other regions.
                            For questions, contact
                            <span> </span>
                            <Link
                                className="text-primary underline underline-offset-4"
                                href={to('//contact')}
                            >
                                Support
                            </Link>
                            .
                        </AlertDescription>
                    </Alert>
                </div>

                <Separator className="my-8" />

                <aside
                    aria-label="Table of contents"
                    className="border-border bg-card mb-10 rounded-lg border p-6"
                >
                    <h2 className="mb-4 text-base font-medium">On this page</h2>
                    <ul className="text-muted-foreground grid gap-2 text-sm sm:grid-cols-2">
                        <li>
                            <a className="hover:text-foreground hover:underline" href="#overview">
                                1. Overview
                            </a>
                        </li>
                        <li>
                            <a
                                className="hover:text-foreground hover:underline"
                                href="#information-we-collect"
                            >
                                2. Information we collect
                            </a>
                        </li>
                        <li>
                            <a
                                className="hover:text-foreground hover:underline"
                                href="#how-we-use-info"
                            >
                                3. How we use information
                            </a>
                        </li>
                        <li>
                            <a
                                className="hover:text-foreground hover:underline"
                                href="#payments-orders"
                            >
                                4. Payments and orders
                            </a>
                        </li>
                        <li>
                            <a
                                className="hover:text-foreground hover:underline"
                                href="#ai-and-content"
                            >
                                5. AI generation and content
                            </a>
                        </li>
                        <li>
                            <a className="hover:text-foreground hover:underline" href="#sharing">
                                6. How we share data
                            </a>
                        </li>
                        <li>
                            <a
                                className="hover:text-foreground hover:underline"
                                href="#international"
                            >
                                7. International transfers (including KR)
                            </a>
                        </li>
                        <li>
                            <a className="hover:text-foreground hover:underline" href="#retention">
                                8. Data retention
                            </a>
                        </li>
                        <li>
                            <a
                                className="hover:text-foreground hover:underline"
                                href="#your-rights"
                            >
                                9. Your rights and choices
                            </a>
                        </li>
                        <li>
                            <a className="hover:text-foreground hover:underline" href="#security">
                                10. Security
                            </a>
                        </li>
                        <li>
                            <a className="hover:text-foreground hover:underline" href="#cookies">
                                11. Cookies and tracking
                            </a>
                        </li>
                        <li>
                            <a className="hover:text-foreground hover:underline" href="#children">
                                12. Children’s privacy
                            </a>
                        </li>
                        <li>
                            <a className="hover:text-foreground hover:underline" href="#changes">
                                13. Changes to this policy
                            </a>
                        </li>
                        <li>
                            <a className="hover:text-foreground hover:underline" href="#contact">
                                14. Contact us
                            </a>
                        </li>
                    </ul>
                </aside>

                <article className="prose prose-slate dark:prose-invert max-w-none">
                    <section id="overview" className="scroll-mt-28">
                        <h2>1. Overview</h2>
                        <p>
                            RealizeIt turns your natural-language requests into purchasable products
                            using AI design generation, with payments processed by Stripe and
                            fulfillment by Printify. We use Supabase for authentication, Postgres
                            data storage, and asset storage. This policy describes what data we
                            collect, how we use it, with whom we share it, and the choices available
                            to you.
                        </p>
                        <p>
                            By using RealizeIt, you agree to this Privacy Policy and our
                            <span> </span>
                            <Link
                                href={to('//legal/terms')}
                                className="text-primary underline underline-offset-4"
                            >
                                Terms of Service
                            </Link>
                            . If you do not agree, please discontinue use.
                        </p>
                    </section>

                    <section id="information-we-collect" className="scroll-mt-28">
                        <h2>2. Information we collect</h2>
                        <p>
                            We collect information you provide directly, information generated
                            through your use of the service, and limited data from partners to
                            provide, secure, and improve the app.
                        </p>

                        <div className="not-prose border-border bg-card mt-6 overflow-hidden rounded-lg border">
                            <Table>
                                <TableCaption className="text-muted-foreground text-xs">
                                    Examples are illustrative and may change as features evolve.
                                </TableCaption>
                                <TableHeader>
                                    <TableRow>
                                        <TableHead>Category</TableHead>
                                        <TableHead>Examples</TableHead>
                                        <TableHead>Source</TableHead>
                                        <TableHead>Retention</TableHead>
                                    </TableRow>
                                </TableHeader>
                                <TableBody>
                                    {dataMap.map((row) => (
                                        <TableRow key={row.category}>
                                            <TableCell className="font-medium">
                                                {row.category}
                                            </TableCell>
                                            <TableCell>{row.examples}</TableCell>
                                            <TableCell>{row.source}</TableCell>
                                            <TableCell>{row.retention}</TableCell>
                                        </TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                        </div>

                        <Collapsible className="not-prose border-border bg-card mt-6 rounded-lg border">
                            <CollapsibleTrigger asChild>
                                <button className="hover:bg-muted flex w-full items-center justify-between rounded-lg px-4 py-3 text-left text-sm font-medium">
                                    Additional details
                                    <span className="text-muted-foreground">Expand</span>
                                </button>
                            </CollapsibleTrigger>
                            <CollapsibleContent className="text-muted-foreground px-4 pt-0 pb-4 text-sm">
                                <ul className="list-disc space-y-2 pl-5">
                                    <li>
                                        We never store raw payment card numbers or CVV. Stripe is
                                        our PCI-DSS compliant processor.
                                    </li>
                                    <li>
                                        We store AI design metadata (e.g., prompts, parameters) to
                                        enable variations, quality checks, and reorders.
                                    </li>
                                    <li>
                                        We do not allow customer image uploads for initial POC; only
                                        AI-generated assets are supported.
                                    </li>
                                </ul>
                            </CollapsibleContent>
                        </Collapsible>
                    </section>

                    <section id="how-we-use-info" className="scroll-mt-28">
                        <h2>3. How we use information</h2>
                        <ul>
                            <li>Provide, maintain, and improve the service and product catalog.</li>
                            <li>
                                Create design briefs using Solar Pro2 and generate artwork with
                                configured image APIs.
                            </li>
                            <li>
                                Compose print-ready files, manage mockups, and facilitate
                                auto-submission to Printify.
                            </li>
                            <li>
                                Process payments and prevent fraud via Stripe and internal risk
                                checks.
                            </li>
                            <li>
                                Send transactional emails (order confirmations, shipping, delivery).
                            </li>
                            <li>
                                Provide customer support and handle returns/cancellations where
                                applicable.
                            </li>
                            <li>Comply with legal obligations and enforce our terms.</li>
                            <li>
                                Analyze performance, reliability, and costs to improve quality and
                                control spend.
                            </li>
                        </ul>
                    </section>

                    <section id="payments-orders" className="scroll-mt-28">
                        <h2>4. Payments and orders</h2>
                        <p>
                            Payments are processed by Stripe. We store non-sensitive payment
                            metadata (e.g., payment intent IDs) to reconcile orders. After
                            successful payment, we create and submit your order to Printify using
                            mapped templates and variant IDs. Shipping address details are used to
                            calculate rates and deliver your items.
                        </p>
                        <p>
                            For more on terms and order handling, see our
                            <span> </span>
                            <Link
                                href={to('//legal/terms')}
                                className="text-primary underline underline-offset-4"
                            >
                                Terms of Service
                            </Link>
                            <span> </span>
                            and
                            <span> </span>
                            <Link
                                href={to('//legal/ip-policy')}
                                className="text-primary underline underline-offset-4"
                            >
                                IP Policy
                            </Link>
                            .
                        </p>
                    </section>

                    <section id="ai-and-content" className="scroll-mt-28">
                        <h2>5. AI generation and content</h2>
                        <p>
                            Design prompts you enter and the resulting briefs, parameters, and
                            assets may be used to generate variations and improve quality. We store
                            generated assets and print files in Supabase Storage. We may run
                            automated checks for prohibited content and quality. We do not sell your
                            prompts or designs to third parties.
                        </p>
                        <p>
                            You must ensure your prompts do not infringe third-party rights. Review
                            our
                            <span> </span>
                            <Link
                                href={to('//legal/ip-policy')}
                                className="text-primary underline underline-offset-4"
                            >
                                IP Policy
                            </Link>
                            <span> </span>
                            for details. Consent regarding AI-generated designs may be recorded at
                            checkout and stored with your order.
                        </p>
                    </section>

                    <section id="sharing" className="scroll-mt-28">
                        <h2>6. How we share data</h2>
                        <ul>
                            <li>
                                Service providers: Stripe (payments), Printify (fulfillment), cloud
                                hosting, email delivery, error monitoring, and analytics. These
                                providers process data on our behalf under appropriate agreements.
                            </li>
                            <li>
                                Legal and safety: We may disclose information to comply with law,
                                enforce our policies, or protect rights, property, and safety.
                            </li>
                            <li>
                                Business transfers: In a merger, acquisition, or asset sale, data
                                may be transferred subject to this policy.
                            </li>
                        </ul>

                        <Collapsible className="not-prose border-border bg-card mt-6 rounded-lg border">
                            <CollapsibleTrigger asChild>
                                <button className="hover:bg-muted flex w-full items-center justify-between rounded-lg px-4 py-3 text-left text-sm font-medium">
                                    Our core subprocessors
                                    <span className="text-muted-foreground">Expand</span>
                                </button>
                            </CollapsibleTrigger>
                            <CollapsibleContent className="text-muted-foreground px-4 pt-0 pb-4 text-sm">
                                <ul className="list-disc space-y-2 pl-5">
                                    <li>Supabase (authentication, database, storage)</li>
                                    <li>Stripe (payments, billing, invoices)</li>
                                    <li>Printify (order creation, fulfillment, tracking)</li>
                                    <li>
                                        Generative image API provider(s) configured for artwork
                                        rendering
                                    </li>
                                    <li>
                                        Error monitoring and logging provider(s) for reliability and
                                        security
                                    </li>
                                </ul>
                            </CollapsibleContent>
                        </Collapsible>
                    </section>

                    <section id="international" className="scroll-mt-28">
                        <h2>7. International transfers (including KR)</h2>
                        <p>
                            We operate globally with infrastructure that may process data in
                            multiple regions. Orders destined for South Korea are fulfilled via
                            Printify and regional partners. Where required, we implement safeguards
                            such as standard contractual clauses or equivalent mechanisms.
                        </p>
                    </section>

                    <section id="retention" className="scroll-mt-28">
                        <h2>8. Data retention</h2>
                        <p>
                            We retain information for as long as necessary to provide the service,
                            comply with legal and tax obligations, resolve disputes, and enforce
                            agreements. Retention periods vary by category as noted above. When no
                            longer needed, we delete or anonymize data.
                        </p>
                    </section>

                    <section id="your-rights" className="scroll-mt-28">
                        <h2>9. Your rights and choices</h2>
                        <ul>
                            <li>
                                Access, update, or delete your profile and addresses in
                                <span> </span>
                                <Link
                                    href={to('/account/settings')}
                                    className="text-primary underline underline-offset-4"
                                >
                                    Account Settings
                                </Link>
                                .
                            </li>
                            <li>
                                Download invoices and view order history in your account dashboard.
                            </li>
                            <li>
                                Opt-out of non-essential emails via links provided in the message.
                            </li>
                            <li>
                                Request deletion of your account; legal/tax records may be retained
                                as required.
                            </li>
                            <li>
                                Manage cookies at the browser level. Some features may not function
                                without certain cookies.
                            </li>
                        </ul>

                        <div className="not-prose mt-6 flex flex-wrap gap-3">
                            <Link
                                href={to('/account/settings')}
                                className="bg-primary text-primary-foreground inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium shadow transition hover:opacity-90"
                            >
                                Manage privacy in Settings
                            </Link>
                            <Link
                                href={to('/sign-in')}
                                className="border-input bg-background text-foreground hover:bg-muted inline-flex items-center justify-center rounded-md border px-4 py-2 text-sm font-medium shadow-sm transition"
                            >
                                Sign in to your account
                            </Link>
                        </div>
                    </section>

                    <section id="security" className="scroll-mt-28">
                        <h2>10. Security</h2>
                        <p>
                            We employ technical and organizational measures appropriate to the risk,
                            including encryption in transit, access controls, and monitoring. No
                            system is perfectly secure; please use a strong, unique password and
                            enable additional protections where available.
                        </p>
                    </section>

                    <section id="cookies" className="scroll-mt-28">
                        <h2>11. Cookies and tracking</h2>
                        <p>
                            We use cookies and similar technologies for authentication, session
                            management, analytics, and fraud prevention. You can control cookies
                            through your browser. Blocking essential cookies may impair core
                            functionality like sign-in and checkout.
                        </p>
                    </section>

                    <section id="children" className="scroll-mt-28">
                        <h2>12. Children’s privacy</h2>
                        <p>
                            RealizeIt is not directed to children under the age required by local
                            law to consent to data processing. We do not knowingly collect personal
                            information from children without appropriate consent.
                        </p>
                    </section>

                    <section id="changes" className="scroll-mt-28">
                        <h2>13. Changes to this policy</h2>
                        <p>
                            We may update this policy from time to time. We will revise the “Last
                            updated” date and, when material changes occur, we may notify you via
                            email or in-app notice. Continued use of the service after changes
                            indicates acceptance of the updated policy.
                        </p>
                    </section>

                    <section id="contact" className="scroll-mt-28">
                        <h2>14. Contact us</h2>
                        <p>
                            If you have questions or concerns about this policy or your data, please
                            contact our support team.
                        </p>
                        <div className="not-prose mt-4 flex flex-wrap gap-3">
                            <Link
                                href={to('//contact')}
                                className="bg-primary text-primary-foreground inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium shadow transition hover:opacity-90"
                            >
                                Contact Support
                            </Link>
                            <Link
                                href={to('//help')}
                                className="border-input bg-background text-foreground hover:bg-muted inline-flex items-center justify-center rounded-md border px-4 py-2 text-sm font-medium shadow-sm transition"
                            >
                                Help Center
                            </Link>
                        </div>
                    </section>
                </article>

                <Separator className="my-10" />

                <div className="border-border bg-card grid gap-4 rounded-lg border p-6 sm:grid-cols-2">
                    <div>
                        <h3 className="text-base font-medium">Keep exploring</h3>
                        <p className="text-muted-foreground mt-1 text-sm">
                            Learn more about our platform, create a design, or review your orders.
                        </p>
                    </div>
                    <div className="flex flex-wrap items-center gap-3 sm:justify-end">
                        <Link
                            href={to('//about')}
                            className="border-input bg-background text-foreground hover:bg-muted inline-flex items-center justify-center rounded-md border px-4 py-2 text-sm font-medium shadow-sm transition"
                        >
                            About
                        </Link>
                        <Link
                            href={to('/products')}
                            className="border-input bg-background text-foreground hover:bg-muted inline-flex items-center justify-center rounded-md border px-4 py-2 text-sm font-medium shadow-sm transition"
                        >
                            Products
                        </Link>
                        <Link
                            href={to('/design')}
                            className="bg-primary text-primary-foreground inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium shadow transition hover:opacity-90"
                        >
                            Start designing
                        </Link>
                        <Link
                            href={to('/cart')}
                            className="border-input bg-background text-foreground hover:bg-muted inline-flex items-center justify-center rounded-md border px-4 py-2 text-sm font-medium shadow-sm transition"
                        >
                            Cart
                        </Link>
                        <Link
                            href={to('/checkout')}
                            className="border-input bg-background text-foreground hover:bg-muted inline-flex items-center justify-center rounded-md border px-4 py-2 text-sm font-medium shadow-sm transition"
                        >
                            Checkout
                        </Link>
                    </div>
                </div>

                <div className="text-muted-foreground mt-6 flex flex-wrap items-center gap-3 text-sm">
                    <Link
                        href={to('//legal/terms')}
                        className="hover:text-foreground hover:underline"
                    >
                        Terms of Service
                    </Link>
                    <span className="text-border">•</span>
                    <Link
                        href={to('//legal/ip-policy')}
                        className="hover:text-foreground hover:underline"
                    >
                        IP Policy
                    </Link>
                    <span className="text-border">•</span>
                    <Link
                        href={to('//legal/privacy')}
                        className="hover:text-foreground hover:underline"
                    >
                        Privacy Policy
                    </Link>
                    <span className="text-border">•</span>
                    <Link
                        href={to('/account/settings')}
                        className="hover:text-foreground hover:underline"
                    >
                        Account Settings
                    </Link>
                </div>
            </section>
        </main>
    )
}
