import '../globals.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export const dynamicParams = false

export default async function RootLayout({
    params,
    children,
}: Readonly<{
    params: Promise<{ lang: string }>
    children: React.ReactNode
}>) {
    return (
        <html suppressHydrationWarning lang={(await params).lang}>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {children}
            </body>
        </html>
    )
}
